### ISSUE TITLE
Notes from 5 jul

### ISSUE THREAD

**Issue by mosoriob** [KnowledgeCaptureAndDiscovery/DISK-UI#19]
## Hypothesis viewing

- [x] Hide formal expression
- [x] Don't show the variables using brackets. Use a different color
- [x] #20
- [x] #21
- [x] Rename  `Select a pattern that can express your hypothesis or question:`
- [x] #23
### Executions 

- [x] Rename P value
- [x] Add executions date
- [ ] #30
- [x] Successful is not related to the hypothesis

## LOI view
- [x] After selecting the workflow, the UI doesn't display meta workflow
- [ ] #29
- [x] List of variable -> Column to show on table
- [x] No hide text fields between View and Edit screen

**Comment by hvarg** [comment]
To add question marks we need to update https://github.com/KnowledgeCaptureAndDiscovery/QuestionOntology/blob/main/examples/hypothesisQuestions.xml
