### ISSUE TITLE
Allow to query the data source from LOI view

### ISSUE THREAD

**Issue by mosoriob** [KnowledgeCaptureAndDiscovery/DISK-UI#9]

**Comment by mosoriob** [comment]
![image](https://user-images.githubusercontent.com/2365990/172869235-817f6483-aa4f-41db-9fcb-e17290717008.png)

**Comment by hvarg** [comment]
added on https://github.com/KnowledgeCaptureAndDiscovery/DISK-UI/commit/b9d58976e02d2b4be3e97150fa5d616d0f72c634
